### PR TITLE
Fix iOS issues. Upgrade to latest version of SystemJS. Replace fat ar…

### PR DESCRIPTION
**Pull request by mdgbayly**
…row functions with es5 functions

### CODE REVIEW

**Comment by mdgbayly** [comment]
Hi

I think this library was perhaps upgraded to a later babel version, but no presets or plugins were added so the fat arrow functions started breaking in iOS Safari  I guess I could have added the babel plugins, but was easier for me to get it working and tested by just switching to regular functions.  Hope you don't mind. Feel free to disregard/redo.

Martin

**Comment by dbatiste** [comment]
Interesting.  If the result of babelify on arrow functions does not work in iOS, there could be some other apps affected.  I'd be interested in getting to the bottom of that.  I think the runtime is probably only included for Promise.  The runtime tries to emulate a full ES6 environment, and it tends to bloat the bundle.  Given that, to get promise functionality, I'd tend to prefer using [lie](https://www.npmjs.com/package/lie).

**Comment by mdgbayly** [comment]
My assumption is that it's not that babelify of fat arrow functions doesn't work on iOS. I think it's more that at some point the version of babel in this project was probably upgraded to 6+. In babel 6, by default you get no or minimal e6 support and instead you have to explicitly specify presets or plugins.  I don't think this project is specifying any in it's browserify cmd and doesn't have a babel.rc so by default babel isn't doing much.

**Comment by mdgbayly** [comment]
I added some css tweaks to the hello-world-fra-iframe, to fix an issue with scrolling in iOS when using VoiceOver. 

VoiceOver uses a page based mechanism to allow the user to scroll the page using a 3 finger drag gesture.  

I hit an issue with our question editor, where you can scroll the page down then up when the page is first displayed, but then you can no longer scroll.  hello-world-fra-ifram has the same issue.  I narrowed this down to issues caused by ifrau/iframe-resizer setting the iframe height as a style on the fra's iframe.  If the height is set incorrectly (less than the actual height of the fra page) then the scrolling issue presents itself.

The fix was to tweak the css to make it easier for iframe-resizer to correctly calculate the page height.

I believe our iframe-resizer integration is using the default calculation method:
https://github.com/davidjbradshaw/iframe-resizer#heightcalculationmethod

This doesn't correctly calculate the size in a scenario like the following because the h1 margin is collapsed into the margin of the body element.  So the actual margin of the document is 30px but this is not taken into account by iframe-resizer.  So you end up with a body element that is smaller than the html element and the iframe height is set to be too small.

    <body style="margin:0">
        <h1 style="margin-top:30px">How now brown cow</h1>
    </body>

The workaround I've used for the question editor is to add a body margin-top matching the h1 margin, and I've added that same workaround to this hello world fra.

Maybe it would be better to see if we should be using a different height calculation method, but that seems to be opening up a can of worms, and this is a quick and understandable solution once you are aware of the issue.

**Comment by dbatiste** [comment]
Hey Martin, if one doesn't already exist, it would probably be worthwhile logging an issue in `ifrau` and getting in touch with one of the contributors for `ifrau` re the sizing issue.  I think a couple of those guys are much more aware of the limitations of `iframe-resizer`, and the value we get out of it, so they'd be best to comment on solution.

**Comment by dlockhart** [comment]
Closing due to age.

**Pull request closed without merging**
